name: ci
on: ["push"]

jobs:
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Setup
        run: |
          python -m pip install 'uv~=0.2.11'
          python -m uv --version
          python -m uv pip install --verbose 'antlr4-python3-runtime==4.9.3'

